import React, { createContext, useContext, useState, useEffect } from 'react';

const UserContext = createContext();

const API_BASE_URL = 'http://localhost:8080/api/v1';

export const useUsers = () => useContext(UserContext);

export const UserProvider = ({ children }) => {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/usuario`);
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      const data = await response.json();
      setUsers(data);
    } catch (error) {
      console.error('Erro ao buscar usu치rios:', error);
    }
  };

  const addUser = async (user) => {
    try {
      const response = await fetch(`${API_BASE_URL}/usuario`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(user),
      });
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      const newUser = await response.json();
      setUsers([...users, newUser]);
    } catch (error) {
      console.error('Erro ao adicionar usu치rio:', error);
      throw error;
    }
  };

  const updateUser = async (updatedUser) => {
    try {
      const response = await fetch(`${API_BASE_URL}/usuario/${updatedUser.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(updatedUser),
      });
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      const data = await response.json();
      setUsers(users.map(u => u.id === updatedUser.id ? data : u));
    } catch (error) {
      console.error('Erro ao atualizar usu치rio:', error);
      throw error;
    }
  };

  const deleteUser = async (userId) => {
    try {
      const response = await fetch(`${API_BASE_URL}/usuario/${userId}`, {
        method: 'DELETE',
      });
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      setUsers(users.filter(u => u.id !== userId));
      return true;
    } catch (error) {
      console.error('Erro ao deletar usu치rio:', error);
      throw error;
    }
  };

  return (
    <UserContext.Provider value={{ users, addUser, updateUser, deleteUser }}>
      {children}
    </UserContext.Provider>
  );
};